version: '3.9'

services:
  dokku:
    image: dokku/dokku:0.36.7
    container_name: dokku
    restart: unless-stopped
    environment:
      DOKKU_HOSTNAME: ${DOKKU_HOSTNAME}
    ports:
      - "3022:22"
      - "8080:80"
      - "8443:443"
    volumes:
      - ~/.ssh/id_rsa.pub:/root/.ssh/authorized_keys:ro
      - /var/run/docker.sock:/var/run/docker.sock

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: unless-stopped
    depends_on:
      - dokku
    command: tunnel run
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}

